name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7
      - name: Install dependencies
        run: dotnet restore
      - name: Build release
        run: dotnet build --configuration Release --no-restore
      - name: Test & Coverage
        run:
          dotnet test --no-restore --collect:"XPlat Code Coverage" --settings ./build/coverage.runsettings -v n
          # dotnet test --no-restore --collect:"XPlat Code Coverage" --settings ./build/coverage.runsettings -v n -r .build/
